# Change these first
owner: switch-software-solutions # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Pase Libre API
    url: https://api.paselibre.uy/api/health/liveness
    icon: https://paselibre.uy/assets/images/paselibreLogo.svg
  - name: Pase Libre WebSite
    url: https://paselibre.uy
    icon: https://paselibre.uy/assets/images/paselibreLogo.svg

  - name: SBI Institucional
    url: https://sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg
  - name: SBI Mi Auto
    url: https://miauto.sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg
  - name: SBI Mi Hogar
    url: https://mihogar.sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg
  - name: SBI Backoffice
    url: https://back.sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg
  - name: SBI Autogestion
    url: https://autogestion.sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg
  - name: SBI Corredores
    url: https://corredores.sbi.uy
    icon: https://sbi.uy/assets/images/logos/logo-SBI.svg

  - name: The Real Scout
    url: https://therealscout.com
    icon: https://therealscout.com/assets/images/logos/after90-logo.png
  - name: The Real Scout Backoffice
    url: https://backoffice.therealscout.com
    icon: https://therealscout.com/assets/images/logos/after90-logo.png
  - name: The Real Scout Gateway
    url: https://gateway.therealscout.com/identity
    icon: https://therealscout.com/assets/images/logos/after90-logo.png
    expectedStatusCodes:
      - 404

  - name: Cadynce Web Portal
    url: https://cadynce-web-prod.azurewebsites.net
    icon: https://cadynce-web-prod.azurewebsites.net/assets/images/logos/cadynceLogoColor.svg
  - name: Cadynce Identity API
    url: https://cadynce-api-identity-prod.azurewebsites.net/index.html
    icon: https://cadynce-web-prod.azurewebsites.net/assets/images/logos/cadynceLogoColor.svg
  - name: Cadynce Elements API
    url: https://cadynce-api-elements-prod.azurewebsites.net/index.html
    icon: https://cadynce-web-prod.azurewebsites.net/assets/images/logos/cadynceLogoColor.svg
  - name: Cadynce Files API
    url: https://cadynce-fileserver-prod.azurewebsites.net/index.html
    icon: https://cadynce-web-prod.azurewebsites.net/assets/images/logos/cadynceLogoColor.svg
  - name: Cadynce Elements API
    url: https://cadyncebpa-prod-api-management.azure-api.net
    icon: https://cadynce-web-prod.azurewebsites.net/assets/images/logos/cadynceLogoColor.svg
    expectedStatusCodes:
      - 404

  - name: CEPI WebSite
    url: http://web-cau-prod.switch.com.uy
  - name: CEPI Gateway
    url: http://api-cau-prod.switch.com.uy/api/health/liveness

assignees:
  - amontesdioca-sw
  - mtorterolo-sw
  - dsilveira-sw


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.switchsoftware.us
  # baseUrl: /status-page
  logoUrl: https://switchsoftware.us/assets/images/logos/logo_switch.svg
  name: Switch Software Solutions
  introTitle: "Monitor de aplicaciones desarrolladas por Switch Software Solutions"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
